DATASET:
  NAME: "FGVCAircraft"
  ROOT: "C:/repos/2025-1/research2/CoOp-main/datasets"

DATALOADER:
  TEST:
    BATCH_SIZE: 100
  NUM_WORKERS: 8

INPUT:
  SIZE: (224, 224)
  TRANSFORMS: ["random_resized_crop", "random_flip", "normalize"]

MODEL:
  BACKBONE:
    NAME: "ViT-B/16"

TRAINER:
  NAME: "ZeroshotCLIP"

# python train.py --config configs/trainers/DuOp/zeroclipR.yaml --eval-only