DATASET:
  NAME: "Food101"
  ROOT: "C:/repos/2025-1/research2/CoOp-main/datasets"

DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 1
  TEST:
    BATCH_SIZE: 100
  NUM_WORKERS: 8

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
  TRANSFORMS: ["random_resized_crop", "random_flip", "normalize"]

MODEL:
  BACKBONE:
    NAME: "ViT-B/16"

TRAINER:
  NAME: "ZeroshotCLIP"
  DUOP:
    N_CTX: 4
    CTX_INIT: "a photo of a"
    PREC: "fp16"